lane :test do
  #https://sharethemeal.org/de/checkout.html?userhash=&amount=0.4&version=2&beneficiaryUri=&beneficiarySource=contentful&thankYouUri=aqbZxjtqM0KIKUcWO6Eik
  sharethemeal(
                  amount: "0.4",
                  url: "https://sharethemeal.org/de/checkout.html?userhash=xxxxxx&lang=de&currency=EUR&symbol=€&amount=0.4&version=2&beneficiaryUri=40uvWurduw2QWci42KM4M&beneficiarySource=contentful&thankYouUri=aqbZxjtqM0KIKUcWO6Eik"
               )
end
